name: docs

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4


      - name: Build site
        run: make

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
